export default {
  products: [
    {
      id: "1",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/img/product_1.png",
      price: 60,
      brand: "US Polo",
      rating: 4.5,
      numReviews: 10,
      year: 2020,
      sale: false,
      countInStock: 0,
    },
    {
      id: "2",
      name: "Big Shirt",
      category: "Shirts",
      image: "/img/product_1.png",
      price: 30,
      brand: "US Polo",
      rating: 3,
      numReviews: 4,
      year: 2019,
      sale: true,
      countInStock: 4,
    },
    {
      id: "3",
      name: "Small Pants",
      category: "Pants",
      image: "/img/product_1.png",
      price: 32,
      brand: "US Polo",
      rating: 2,
      numReviews: 11,
      year: 2020,
      sale: true,
      countInStock: 2,
    },
    {
      id: "4",
      name: "Small Pants",
      category: "Pants",
      image: "/img/product_1.png",
      price: 24,
      brand: "US Polo",
      rating: 2,
      numReviews: 11,
      year: 2020,
      sale: true,
      countInStock: 12,
    },
    {
      id: "5",
      name: "Small Pants",
      category: "Pants",
      image: "/img/product_1.png",
      price: 24,
      brand: "US Polo",
      rating: 2,
      numReviews: 11,
      year: 2020,
      sale: true,
      countInStock: 22,
    },
  ],
};
